### ISSUE TITLE
How to center buttons in Action Editor?

### ISSUE THREAD

**Issue by slrgt** [BlenderBoi/timeline-buttons#2]
Love this addon and it should be default in Blender! Only issue I have is I can't seem to center the buttons in the Action Editor
![blender_mrmfnBvGfH](https://github.com/user-attachments/assets/d6c3fc66-8e99-4ba4-977d-494b31df2559)

**Comment by BlenderBoi** [comment]
Unfortunately, I don't know how either, i would have center it if I know how though
